import React from 'react';

const Section = ({ title, children }) => (
    <div className="mb-10">
        <h2 className="font-display text-2xl font-bold text-neutral-900 mb-4 pb-2 border-b border-neutral-200">{title}</h2>
        {children}
    </div>
);

const SubSection = ({ title, children }) => (
    <div className="mb-6">
        <h3 className="text-lg font-semibold text-neutral-800 mb-3">{title}</h3>
        {children}
    </div>
);

const SubSubSection = ({ title, children }) => (
    <div className="mb-4">
        <h4 className="text-base font-semibold text-neutral-700 mb-2">{title}</h4>
        {children}
    </div>
);

const P = ({ children }) => (
    <p className="text-neutral-600 leading-relaxed mb-3">{children}</p>
);

const UL = ({ children }) => (
    <ul className="list-disc list-outside ml-5 space-y-2 text-neutral-600 leading-relaxed mb-3">{children}</ul>
);

const PrivacyPolicyPage = () => {
    return (
        <div className="min-h-screen bg-neutral-50">
            {/* Hero Banner */}
            <div className="bg-gradient-to-r from-primary to-primary/80 py-16 px-6">
                <div className="max-w-3xl mx-auto text-center">
                    <h1 className="font-display text-4xl md:text-5xl font-bold text-white mb-3">Privacy Policy</h1>
                    <p className="text-white/70 text-sm">Last updated: June 13, 2026</p>
                </div>
            </div>

            {/* Content */}
            <div className="max-w-3xl mx-auto px-6 py-14">
                <P>
                    This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your
                    information when You use the Service and tells You about Your privacy rights and how the law protects You.
                </P>
                <P>
                    We use Your Personal Data to provide and improve the Service. By using the Service, You agree to the
                    collection and use of information in accordance with this Privacy Policy.
                </P>

                <Section title="Interpretation and Definitions">
                    <SubSection title="Interpretation">
                        <P>
                            The words whose initial letters are capitalized have meanings defined under the following conditions.
                            The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.
                        </P>
                    </SubSection>

                    <SubSection title="Definitions">
                        <P>For the purposes of this Privacy Policy:</P>
                        <UL>
                            <li><strong>Account</strong> means a unique account created for You to access our Service or parts of our Service.</li>
                            <li><strong>Affiliate</strong> means an entity that controls, is controlled by, or is under common control with a party, where "control" means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.</li>
                            <li><strong>Company</strong> (referred to as either "the Company", "We", "Us" or "Our" in this Privacy Policy) refers to Sindhi Namkeen DryFruit.</li>
                            <li><strong>Cookies</strong> are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.</li>
                            <li><strong>Country</strong> refers to: Haryana, India</li>
                            <li><strong>Device</strong> means any device that can access the Service such as a computer, a cell phone or a digital tablet.</li>
                            <li><strong>Personal Data</strong> (or "Personal Information") is any information that relates to an identified or identifiable individual. We use "Personal Data" and "Personal Information" interchangeably unless a law uses a specific term.</li>
                            <li><strong>Service</strong> refers to the Website.</li>
                            <li><strong>Service Provider</strong> means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.</li>
                            <li><strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</li>
                            <li><strong>Website</strong> refers to Sindhi Namkeen DryFruit, accessible from <span className="text-primary font-medium">sindhinamkeendryfruit.com</span>.</li>
                            <li><strong>You</strong> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</li>
                        </UL>
                    </SubSection>
                </Section>

                <Section title="Collecting and Using Your Personal Data">
                    <SubSection title="Types of Data Collected">
                        <SubSubSection title="Personal Data">
                            <P>
                                While using Our Service, We may ask You to provide Us with certain personally identifiable information
                                that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:
                            </P>
                            <UL>
                                <li>Email address</li>
                                <li>First name and last name</li>
                                <li>Phone number</li>
                                <li>Address, State, Province, ZIP/Postal code, City</li>
                            </UL>
                        </SubSubSection>

                        <SubSubSection title="Usage Data">
                            <P>Usage Data is collected automatically when using the Service.</P>
                            <P>
                                Usage Data may include information such as Your Device's Internet Protocol address (e.g. IP address),
                                browser type, browser version, the pages of our Service that You visit, the time and date of Your visit,
                                the time spent on those pages, unique device identifiers and other diagnostic data.
                            </P>
                            <P>
                                When You access the Service by or through a mobile device, We may collect certain information automatically,
                                including, but not limited to, the type of mobile device You use, Your mobile device's unique ID, the IP address
                                of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, unique device
                                identifiers and other diagnostic data.
                            </P>
                            <P>
                                We may also collect information that Your browser sends whenever You visit Our Service or when You access the
                                Service by or through a mobile device.
                            </P>
                        </SubSubSection>

                        <SubSubSection title="Tracking Technologies and Cookies">
                            <P>
                                We use Cookies and similar tracking technologies to track the activity on Our Service and store certain
                                information. Tracking technologies We use include beacons, tags, and scripts to collect and track information
                                and to improve and analyze Our Service. The technologies We use may include:
                            </P>
                            <UL>
                                <li><strong>Cookies or Browser Cookies.</strong> A cookie is a small file placed on Your Device. You can instruct Your browser to refuse all Cookies or to indicate when a Cookie is being sent. However, if You do not accept Cookies, You may not be able to use some parts of our Service.</li>
                                <li><strong>Web Beacons.</strong> Certain sections of our Service and our emails may contain small electronic files known as web beacons (also referred to as clear gifs, pixel tags, and single-pixel gifs) that permit the Company, for example, to count users who have visited those pages or opened an email and for other related website statistics.</li>
                            </UL>
                            <P>
                                Cookies can be "Persistent" or "Session" Cookies. Persistent Cookies remain on Your personal computer or
                                mobile device when You go offline, while Session Cookies are deleted as soon as You close Your web browser.
                            </P>
                            <P>
                                Where required by law, we use non-essential cookies only with Your consent. You can withdraw or change Your
                                consent at any time through Your browser/device settings.
                            </P>
                            <P>We use both Session and Persistent Cookies for the purposes set out below:</P>
                            <UL>
                                <li>
                                    <strong>Necessary / Essential Cookies</strong> — Type: Session Cookies. Purpose: These Cookies are essential to provide You with services available through the Website and to enable You to use some of its features. They help to authenticate users and prevent fraudulent use of user accounts.
                                </li>
                                <li>
                                    <strong>Cookies Policy / Notice Acceptance Cookies</strong> — Type: Persistent Cookies. Purpose: These Cookies identify if users have accepted the use of cookies on the Website.
                                </li>
                                <li>
                                    <strong>Functionality Cookies</strong> — Type: Persistent Cookies. Purpose: These Cookies allow Us to remember choices You make when You use the Website, such as remembering your login details or language preference.
                                </li>
                            </UL>
                        </SubSubSection>
                    </SubSection>

                    <SubSection title="Use of Your Personal Data">
                        <P>The Company may use Personal Data for the following purposes:</P>
                        <UL>
                            <li><strong>To provide and maintain our Service</strong>, including to monitor the usage of our Service.</li>
                            <li><strong>To manage Your Account:</strong> to manage Your registration as a user of the Service.</li>
                            <li><strong>For the performance of a contract:</strong> the development, compliance and undertaking of the purchase contract for the products, items or services You have purchased or of any other contract with Us through the Service.</li>
                            <li><strong>To contact You:</strong> To contact You by email, telephone calls, SMS, or other equivalent forms of electronic communication regarding updates or informative communications related to the functionalities, products or contracted services.</li>
                            <li><strong>To provide You</strong> with news, special offers, and general information about other goods, services and events which We offer that are similar to those that you have already purchased or inquired about.</li>
                            <li><strong>To manage Your requests:</strong> To attend and manage Your requests to Us.</li>
                            <li><strong>For business transfers:</strong> We may use Your Personal Data to evaluate or conduct a merger, divestiture, restructuring, reorganization, dissolution, or other sale or transfer of some or all of Our assets.</li>
                            <li><strong>For other purposes:</strong> We may use Your information for other purposes, such as data analysis, identifying usage trends, determining the effectiveness of our promotional campaigns and to evaluate and improve our Service.</li>
                        </UL>
                        <P>We may share Your Personal Data in the following situations:</P>
                        <UL>
                            <li><strong>With Service Providers:</strong> We may share Your Personal Data with Service Providers to monitor and analyze the use of our Service, to contact You.</li>
                            <li><strong>For business transfers:</strong> We may share or transfer Your Personal Data in connection with any merger, sale of Company assets, financing, or acquisition.</li>
                            <li><strong>With Affiliates:</strong> We may share Your Personal Data with Our affiliates, in which case we will require those affiliates to honor this Privacy Policy.</li>
                            <li><strong>With business partners:</strong> We may share Your Personal Data with Our business partners to offer You certain products, services or promotions.</li>
                            <li><strong>With Your consent:</strong> We may disclose Your Personal Data for any other purpose with Your consent.</li>
                        </UL>
                    </SubSection>

                    <SubSection title="Retention of Your Personal Data">
                        <P>
                            The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in
                            this Privacy Policy. We will retain and use Your Personal Data to the extent necessary to comply with our
                            legal obligations, resolve disputes, and enforce our legal agreements and policies.
                        </P>
                        <P>We apply different retention periods to different categories of Personal Data:</P>
                        <UL>
                            <li><strong>Account Information:</strong> retained for the duration of your account relationship plus up to 24 months after account closure.</li>
                            <li><strong>Customer Support Data:</strong> support tickets and correspondence up to 24 months from the date of ticket closure.</li>
                            <li><strong>Usage Data:</strong> website analytics data up to 24 months from the date of collection. Server logs up to 24 months for security monitoring.</li>
                        </UL>
                        <P>
                            We may retain Personal Data beyond the periods stated above where required by legal obligation, for legal
                            claims, at Your explicit request, or due to technical limitations such as encrypted backup schedules.
                        </P>
                        <P>
                            When retention periods expire, We securely delete or anonymize Personal Data. In some cases, We convert
                            Personal Data into anonymous statistical data that cannot be linked back to You.
                        </P>
                    </SubSection>

                    <SubSection title="Transfer of Your Personal Data">
                        <P>
                            Your information, including Personal Data, is processed at the Company's operating offices and in any other
                            places where the parties involved in the processing are located. It means that this information may be
                            transferred to — and maintained on — computers located outside of Your state, province, country or other
                            governmental jurisdiction where the data protection laws may differ from those from Your jurisdiction.
                        </P>
                        <P>
                            The Company will take all steps reasonably necessary to ensure that Your data is treated securely and in
                            accordance with this Privacy Policy and no transfer of Your Personal Data will take place to an organization
                            or a country unless there are adequate controls in place.
                        </P>
                    </SubSection>

                    <SubSection title="Delete Your Personal Data">
                        <P>You have the right to delete or request that We assist in deleting the Personal Data that We have collected about You.</P>
                        <P>
                            You may update, amend, or delete Your information at any time by contacting Us to request access to, correct,
                            or delete any Personal Data that You have provided to Us.
                        </P>
                        <P>Please note, however, that We may need to retain certain information when we have a legal obligation or lawful basis to do so.</P>
                    </SubSection>

                    <SubSection title="Disclosure of Your Personal Data">
                        <SubSubSection title="Business Transactions">
                            <P>
                                If the Company is involved in a merger, acquisition or asset sale, Your Personal Data may be transferred.
                                We will provide notice before Your Personal Data is transferred and becomes subject to a different Privacy Policy.
                            </P>
                        </SubSubSection>
                        <SubSubSection title="Law Enforcement">
                            <P>
                                Under certain circumstances, the Company may be required to disclose Your Personal Data if required to do
                                so by law or in response to valid requests by public authorities (e.g. a court or a government agency).
                            </P>
                        </SubSubSection>
                        <SubSubSection title="Other Legal Requirements">
                            <P>The Company may disclose Your Personal Data in the good faith belief that such action is necessary to:</P>
                            <UL>
                                <li>Comply with a legal obligation</li>
                                <li>Protect and defend the rights or property of the Company</li>
                                <li>Prevent or investigate possible wrongdoing in connection with the Service</li>
                                <li>Protect the personal safety of Users of the Service or the public</li>
                                <li>Protect against legal liability</li>
                            </UL>
                        </SubSubSection>
                    </SubSection>

                    <SubSection title="Security of Your Personal Data">
                        <P>
                            The security of Your Personal Data is important to Us, but remember that no method of transmission over
                            the Internet, or method of electronic storage is 100% secure. While We strive to use commercially reasonable
                            means to protect Your Personal Data, We cannot guarantee its absolute security.
                        </P>
                    </SubSection>
                </Section>

                <Section title="Children's Privacy">
                    <P>
                        Our Service does not address anyone under the age of 16. We do not knowingly collect personally identifiable
                        information from anyone under the age of 16. If You are a parent or guardian and You are aware that Your child
                        has provided Us with Personal Data, please contact Us. If We become aware that We have collected Personal Data
                        from anyone under the age of 16 without verification of parental consent, We take steps to remove that
                        information from Our servers.
                    </P>
                </Section>

                <Section title="Links to Other Websites">
                    <P>
                        Our Service may contain links to other websites that are not operated by Us. If You click on a third party link,
                        You will be directed to that third party's site. We strongly advise You to review the Privacy Policy of every site You visit.
                    </P>
                    <P>
                        We have no control over and assume no responsibility for the content, privacy policies or practices of any
                        third party sites or services.
                    </P>
                </Section>

                <Section title="Changes to this Privacy Policy">
                    <P>
                        We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new
                        Privacy Policy on this page.
                    </P>
                    <P>
                        We will let You know via email and/or a prominent notice on Our Service, prior to the change becoming effective
                        and update the "Last updated" date at the top of this Privacy Policy.
                    </P>
                    <P>
                        You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are
                        effective when they are posted on this page.
                    </P>
                </Section>

                <Section title="Contact Us">
                    <P>If you have any questions about this Privacy Policy, You can contact us:</P>
                    <div className="inline-flex items-center gap-3 bg-primary/5 border border-primary/20 rounded-xl px-5 py-3">
                        <span className="text-neutral-600">By email:</span>
                        <a
                            href="mailto:sindhinamkeen250@gmail.com"
                            className="text-primary font-semibold hover:underline"
                        >
                            sindhinamkeen250@gmail.com
                        </a>
                    </div>
                </Section>
            </div>
        </div>
    );
};

export default PrivacyPolicyPage;
